# Generated by Django 4.2.7 on 2025-10-24 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0004_notification'),
        ('payment', '0003_alter_payment_options_remove_payment_student_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
        migrations.RemoveField(
            model_name='payment',
            name='month',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='year',
        ),
        migrations.AddField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dormitory.student'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Tiền mặt'), ('bank_transfer', 'Chuyển khoản'), ('momo', 'Ví MoMo'), ('zalopay', 'ZaloPay')], default='cash', max_length=20),
        ),
    ]
