# Generated by Django 5.2.7 on 2025-10-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_payment_options_remove_payment_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('room', 'Tiền phòng'), ('electric', 'Tiền điện'), ('water', 'Tiền nước')], default='room', max_length=20),
        ),
    ]
