# Generated by Django 5.2.7 on 2025-10-31 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_payment_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
    ]
