# Generated by Django 5.2.7 on 2025-10-31 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_payment_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='student',
        ),
    ]
