# Generated by Django 5.2.7 on 2025-11-01 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0005_repairrequest'),
        ('payment', '0007_remove_payment_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='dormitory.student'),
        ),
    ]
