# Generated by Django 4.2.7 on 2025-10-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0002_student_date_of_birth_student_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='current_occupancy',
            field=models.IntegerField(default=0),
        ),
    ]
