# Generated by Django 4.2.7 on 2025-10-17 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dormitory', '0003_room_current_occupancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('message', models.TextField(verbose_name='Nội dung')),
                ('notification_type', models.CharField(choices=[('info', '📢 Thông tin'), ('success', '✅ Thành công'), ('warning', '⚠️ Cảnh báo'), ('error', '❌ Lỗi'), ('payment', '💳 Thanh toán'), ('contract', '📄 Hợp đồng'), ('maintenance', '🔧 Bảo trì'), ('booking', '🏠 Đặt phòng')], default='info', max_length=20, verbose_name='Loại thông báo')),
                ('is_read', models.BooleanField(default=False, verbose_name='Đã đọc')),
                ('related_url', models.CharField(blank=True, max_length=200, verbose_name='URL liên quan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Thông báo',
                'verbose_name_plural': 'Thông báo',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', 'created_at'], name='dormitory_n_user_id_b0af28_idx')],
            },
        ),
    ]
